# .github/workflows/build.yml
name: Build Linux

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Linux
    runs-on:  [self-hosted, linux]
    steps:
      - uses: actions/checkout@master
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
          TOOLCHAIN_VERSION: stable
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
